### ISSUE TITLE
Update from ESP-IDF in register pin.

### ISSUE THREAD

**Issue by ReginaldSourn** [Andrey-m/DHT22-lib-for-esp-idf#5]
In this example, you need to register for ESP32 to open the esp_rom_gpio_pad; otherwise, ESP32 can't create the pulse signals.

```c 
esp_rom_gpio_pad_select_gpio(DHT_PIN);
  ```

before 
```c 
    xTaskCreate(&DHT_task, "DHT_task", 2048, NULL, 5, NULL);

```

**Comment by Andrey-m** [comment]
> In this example, you need to register for ESP32 to open the esp_rom_gpio_pad; otherwise, ESP32 can't create the pulse signals.
> 
> ```c
> esp_rom_gpio_pad_select_gpio(DHT_PIN);
> ```
> 
> before
> 
> ```c
>     xTaskCreate(&DHT_task, "DHT_task", 2048, NULL, 5, NULL);
> ```

Hi.

Thanks.
